modLoader="javafml"
loaderVersion="[4,)"
license="Zombie Mobs License"

[[mods]]
modId="zombiemobs"
version="1.0.2"
displayName="ZombieMobs"
authors="Vykket"
logoFile = "icon.png"
logoBlur = false
description='''Adds new zombified enemies, improvements, and fixes to various mechanics related to zombies, and more!'''

[[mixins]]
config="zombiemobs.mixins.json"

[[dependencies.zombiemobs]]
modId="neoforge"
type="required"
versionRange="[21.1.216,)"
ordering="NONE"
side="BOTH"

[[dependencies.zombiemobs]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"
